[tox]
minversion = 3.20.0
envlist = molecule-light
skipsdist = true

[testenv:molecule-light]
deps =
    molecule
    molecule_docker
    ansible
commands =
    molecule test -s light
setenv =
    ANSIBLE_FORCE_COLOR = 1
    ANSIBLE_ROLES_PATH = {toxinidir}/..
