---
- name: Start Vector service
  systemd:
    name: vector
    state: started
    enabled: yes
    daemon_reload: yes
  ignore_errors: true

- name: Restart Vector service
  systemd:
    name: vector
    state: restarted
    daemon_reload: yes
  ignore_errors: true
