---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Wait for container
      wait_for_connection:
        timeout: 60

    - name: Update apt cache
      raw: apt-get update -y
      changed_when: false

    - name: Install python3
      raw: apt-get install -y python3
      changed_when: false

    - name: Install curl
      raw: apt-get install -y curl
      changed_when: false

    - name: Gather facts
      setup:
