---
dependency:
  name: galaxy
  enabled: false
driver:
  name: docker
platforms:
  - name: ubuntu
    image: ubuntu-vector
    pre_build_image: false
    dockerfile: Dockerfile.ubuntu
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
      
  - name: oraclelinux
    image: antmelekhin/docker-systemd:rockylinux-9
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: profile_tasks
      stdout_callback: yaml
  inventory:
    host_vars:
      ubuntu:
        ansible_user: root
      oraclelinux:
        ansible_user: root
    group_vars:
      all:
        vector_version: "0.21.0"
        vector_config:
          data_dir: /var/lib/vector
          sources:
            syslog:
              type: syslog
              address: 0.0.0.0:514
              mode: tcp
          sinks:
            console:
              type: console
              inputs: ["syslog"]
              encoding:
                codec: json

verifier:
  name: ansible

scenario:
  name: default
  test_sequence:
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - verify
    - destroy
