---
- name: Prepare Ubuntu
  hosts: ubuntu
  gather_facts: false
  tasks:
    - name: Wait for container to be ready
      wait_for_connection:
        timeout: 300

    - name: Install wget and curl
      raw: apt-get update && apt-get install -y wget curl
      changed_when: false

    - name: Gather facts
      setup:

- name: Prepare Oracle Linux
  hosts: oraclelinux
  gather_facts: false
  tasks:
    - name: Wait for container to be ready
      wait_for_connection:
        timeout: 300

    - name: Gather facts
      setup:
